-- 菜单初始化
insert into wechat_menu (ID, SN, MENU_NAME, PRIORITY, URL, PARENT_ID, IS_MENU, DESCRIPTION, CREATE_BY, CREATE_TIME, MODIFY_BY, MODIFY_TIME) values('1','root','根路径','1','#','0','1','菜单树根路径','1',CURRENT_TIMESTAMP,'1',CURRENT_TIMESTAMP);
insert into wechat_menu (ID, SN, MENU_NAME, PRIORITY, URL, PARENT_ID, IS_MENU, DESCRIPTION, CREATE_BY, CREATE_TIME, MODIFY_BY, MODIFY_TIME) values('2','sysmgr','系统管理','1','#','0','1','系统管理','1',CURRENT_TIMESTAMP,'1',CURRENT_TIMESTAMP);
insert into wechat_menu (ID, SN, MENU_NAME, PRIORITY, URL, PARENT_ID, IS_MENU, DESCRIPTION, CREATE_BY, CREATE_TIME, MODIFY_BY, MODIFY_TIME) values('3','userMgr','用户管理','1','#','0','1','用户管理','1',CURRENT_TIMESTAMP,'1',CURRENT_TIMESTAMP);
insert into wechat_menu (ID, SN, MENU_NAME, PRIORITY, URL, PARENT_ID, IS_MENU, DESCRIPTION, CREATE_BY, CREATE_TIME, MODIFY_BY, MODIFY_TIME) values('4','menuMgr','菜单管理','1','#','0','1','菜单管理','1',CURRENT_TIMESTAMP,'1',CURRENT_TIMESTAMP);
insert into wechat_menu (ID, SN, MENU_NAME, PRIORITY, URL, PARENT_ID, IS_MENU, DESCRIPTION, CREATE_BY, CREATE_TIME, MODIFY_BY, MODIFY_TIME) values('5','roleMgr','角色管理','1','#','0','1','角色管理','1',CURRENT_TIMESTAMP,'1',CURRENT_TIMESTAMP);

-- 角色初始化
insert into wechat_role (ID, ROLE_NAME, SYSTEM_CODE, CREATE_BY, CREATE_TIME, MODIFY_BY, MODIFY_TIME) values('1','超级管理员','1','1',CURRENT_TIMESTAMP,'1',CURRENT_TIMESTAMP);

-- 角色权限初始化
insert into wechat_role_permission (ROLE_ID, PERMISSION, CREATE_BY, CREATE_TIME, MODIFY_BY, MODIFY_TIME) values('1','sysMgr','1',CURRENT_TIMESTAMP,'1',CURRENT_TIMESTAMP);
insert into wechat_role_permission (ROLE_ID, PERMISSION, CREATE_BY, CREATE_TIME, MODIFY_BY, MODIFY_TIME) values('1','userMgr','1',CURRENT_TIMESTAMP,'1',CURRENT_TIMESTAMP);
insert into wechat_role_permission (ROLE_ID, PERMISSION, CREATE_BY, CREATE_TIME, MODIFY_BY, MODIFY_TIME) values('1','menuMgr','1',CURRENT_TIMESTAMP,'1',CURRENT_TIMESTAMP);
insert into wechat_role_permission (ROLE_ID, PERMISSION, CREATE_BY, CREATE_TIME, MODIFY_BY, MODIFY_TIME) values('1','roleMgr','1',CURRENT_TIMESTAMP,'1',CURRENT_TIMESTAMP);

-- 管理员角色初始化
insert into wechat_user_role (ID, ROLE_ID, USER_ID, CREATE_BY, CREATE_TIME, MODIFY_BY, MODIFY_TIME) values('1','1','1','1',CURRENT_TIMESTAMP,'1',CURRENT_TIMESTAMP);

-- 管理员帐号初始化
insert into wechat_user (ID, LOGIN_NAME, USER_NAME, NICK_NAME, MOBILE_PHONE, EMAIL, PASSWORD, SALT, LOGIN_TIME, USER_IMG, USER_SEX, USER_TYPE, IS_VALID, BOTH_LOGIN, CREATE_BY, CREATE_TIME, MODIFY_BY, MODIFY_TIME) values('1','admin','超级管理员','系统管理员','18888888888','888@888.com','fb7f45075468accc3f4632b5b0fce86d0b7faed5','3f9e837aa11b1ad1',CURRENT_TIMESTAMP,NULL,'1','1','1','1','1',CURRENT_TIMESTAMP,'1',CURRENT_TIMESTAMP);